# Generated by Django 5.2.7 on 2026-06-25 14:14

from django.db import migrations


def add_soulspeak(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Project.objects.get_or_create(
        title='Soulspeak',
        defaults={
            'description': 'A full-stack peer-to-peer emotional support platform featuring real-time chat, secure JWT authentication, and specialized views for members, companions, and admins.',
            'long_description': 'Built a full-stack peer-to-peer emotional support platform using React, Node/Express, and MongoDB with secure JWT authentication and specialized views for members, companions, and admins. Developed a real-time chat system powered by Socket.io and designed an interactive training module with an automated assessment questionnaire to vet and qualify support companions. Implemented safety and moderation features, including a user-generated reporting workflow, Nodemailer-based email verification, and an admin dashboard to handle content moderation and account suspensions.',
            'tech_stack': 'React, Node.js, Express, MongoDB, Socket.io, JWT, Nodemailer',
            'github_url': 'https://github.com/Turja1111/Soulspeak',
            'live_url': 'https://soulspeak-jet.vercel.app/',
            'featured': True,
            'order': 0,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_sums_project'),
    ]

    operations = [
        migrations.RunPython(add_soulspeak),
    ]
