# Generated by Django 5.2.7 on 2026-06-25 14:22

from django.db import migrations


def add_careerbridge(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Project.objects.get_or_create(
        title='CareerBridge',
        defaults={
            'description': 'LinkedIn Job Scraper & Parser with a smart job board, tracking, and real-time analytics dashboard featuring Chart.js visualizations.',
            'long_description': 'Automated Playwright-based scraper that searches 45+ keyword/location combinations, extracts skills/salary/work-type metadata via regex engine, and deduplicates by LinkedIn job ID. Filterable web UI with Bangladesh-relevance scoring, status tracking (new/saved/applied/ignored), and REST API for programmatic access. Real-time aggregation of top skills, salary ranges, work-type distribution, companies, locations, and job trends with Chart.js visualizations.',
            'tech_stack': 'Python, Playwright, Django, React, Chart.js, PostgreSQL, REST API',
            'github_url': 'https://github.com/Turja1111/CareerBridge',
            'live_url': '',
            'featured': True,
            'order': 1,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_soulspeak_project'),
    ]

    operations = [
        migrations.RunPython(add_careerbridge),
    ]
