# Generated by Django 5.2.7 on 2026-06-25 14:30

from django.db import migrations


def fix_order(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    ordering = [
        'SUMS - Smart University Management System',
        'CareerBridge',
        'Soulspeak',
    ]
    for i, title in enumerate(ordering):
        Project.objects.filter(title=title).update(order=i)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_careerbridge_project'),
    ]

    operations = [
        migrations.RunPython(fix_order),
    ]
