# Generated by Django 5.2.7 on 2026-06-25 14:31

from django.db import migrations


def update_desc(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Project.objects.filter(title='CareerBridge').update(
        description='A full-featured LinkedIn job intelligence platform with an automated Playwright scraper covering 45+ keyword/location combinations, a smart job board with Bangladesh-relevance scoring and status tracking, and a real-time analytics dashboard that visualizes top skills, salary trends, and work-type distribution using Chart.js.',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fix_project_order'),
    ]

    operations = [
        migrations.RunPython(update_desc),
    ]
