# Generated by Django 5.2.7 on 2026-06-25 14:32

from django.db import migrations


def update_url(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Project.objects.filter(title='SUMS - Smart University Management System').update(
        live_url='https://smart-university-management-system.onrender.com/login/'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_careerbridge_desc'),
    ]

    operations = [
        migrations.RunPython(update_url),
    ]
